<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Login</name>
   <tag></tag>
   <elementGuidId>6240a210-6bad-49a3-a003-184c07fb7c52</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#password_welcome_login</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='password_welcome_login']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Enter Password *&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>2b916ee9-f7ec-4d6c-8c00-3192a5eea9e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>password_welcome_login</value>
      <webElementGuid>e3371eb6-92e3-4b09-bdcf-22757c3a2376</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>password_welcome_login</value>
      <webElementGuid>264e33b5-db4e-425b-9805-cf8b7b9d0095</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>textfield-v2--input undefined css-1n65q6j</value>
      <webElementGuid>621af7f1-f6f2-4da8-b949-0604e0a2d316</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>6ba96388-38f6-4d11-8944-35146dd2e64c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;password_welcome_login&quot;)</value>
      <webElementGuid>85cb814f-e632-4fc7-b3b0-2fcf2971cd9c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='password_welcome_login']</value>
      <webElementGuid>16a263a3-41d0-4e91-9108-98d25d1d7ea0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='user-login']/div/div[2]/div/div/input</value>
      <webElementGuid>9db31cf5-713e-45b4-b465-e2ca294a0de7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/input</value>
      <webElementGuid>67e10f48-3a20-45f9-873c-030f19216f79</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'password_welcome_login' and @name = 'password_welcome_login' and @type = 'password']</value>
      <webElementGuid>06d560f1-f574-4695-81d1-d5f9e75cd552</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
