<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Email</name>
   <tag></tag>
   <elementGuidId>43a14c66-8848-4dab-b2c3-e44b34061bfc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#username_welcome_page</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='username_welcome_page']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Your Email id or Phone no *&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>68cb219c-f6a4-48f2-a884-73a019fa51c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>username_welcome_page</value>
      <webElementGuid>a38021af-009c-4515-8966-a3b058572d94</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>username_welcome_page</value>
      <webElementGuid>8f351a80-d99e-4ec5-b656-009e10ec6908</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>textfield-v2--input undefined css-1n65q6j</value>
      <webElementGuid>d0872ade-fe25-4873-932c-26ae4a0d260c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;username_welcome_page&quot;)</value>
      <webElementGuid>f4685c01-2d64-4906-9864-c1c10d87db90</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='username_welcome_page']</value>
      <webElementGuid>5053c253-be25-499a-a67b-e69dcae18a6b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='start-login']/div/div/input</value>
      <webElementGuid>e5211658-75dd-4578-b020-cd82006d91d1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div/div/input</value>
      <webElementGuid>ec073722-1bb7-4c0e-b9a1-b055449dd83a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'username_welcome_page' and @name = 'username_welcome_page']</value>
      <webElementGuid>098f8e24-8a02-4dd4-b8b7-39135296ef1d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
