<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_LoginRegister</name>
   <tag></tag>
   <elementGuidId>9ce4e827-3cb1-4777-a521-4d57513676ec</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.cta-content.flexbox-center > span</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='ulj-login']/span/div/div/div/div/button/span/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Login/Register&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>b2a3af1b-503a-4c81-a62c-ac8a8efafeac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Login/Register</value>
      <webElementGuid>92c3089f-d4a0-4323-8ff7-89ed4d5c8e4b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[1]/div[@class=&quot;css-109h5uy&quot;]/div[@class=&quot;css-1n5qleo&quot;]/div[@class=&quot;MuiGrid-root MuiGrid-container MuiGrid-item MuiGrid-grid-xs-11 MuiGrid-grid-sm-11 MuiGrid-grid-md-11 MuiGrid-grid-lg-11 MuiGrid-grid-xl-10 css-70ai0r&quot;]/div[@class=&quot;css-1iult4i&quot;]/div[@class=&quot;css-j8e9k&quot;]/div[@class=&quot;css-1lrxf2h&quot;]/div[@id=&quot;ulj-login&quot;]/span[1]/div[@class=&quot;ulj-login&quot;]/div[@class=&quot;ulj-login-container&quot;]/div[@class=&quot;ulj-login-container-button&quot;]/div[@class=&quot;ulj-login-desktop&quot;]/button[@class=&quot;MuiButtonBase-root MuiButton-root MuiButton-text MuiButton-textPrimary MuiButton-sizeMedium MuiButton-textSizeMedium MuiButton-colorPrimary MuiButton-root MuiButton-text MuiButton-textPrimary MuiButton-sizeMedium MuiButton-textSizeMedium MuiButton-colorPrimary flex css-t30zi&quot;]/span[@class=&quot;cta-content flexbox-center&quot;]/span[1]</value>
      <webElementGuid>9437f46a-4db4-4398-9d12-cb2f392ff37f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ulj-login']/span/div/div/div/div/button/span/span</value>
      <webElementGuid>f7b66964-08f5-4c32-be21-04eab8d35f5d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Digital Library'])[1]/following::span[3]</value>
      <webElementGuid>6c7ec9af-79ba-4e0b-b69d-c7544800512a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Enterprise Solutions'])[1]/following::span[4]</value>
      <webElementGuid>fe2eb1e7-a7e2-482c-90fe-22133c5c5359</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Login'])[1]/preceding::span[2]</value>
      <webElementGuid>0bf9b22f-2979-40fd-99b2-0867faeecf94</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Learning for'])[1]/preceding::span[5]</value>
      <webElementGuid>3f171271-78db-4eb8-8170-9ed25e1162b3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Login/Register']/parent::*</value>
      <webElementGuid>1de0a798-d98c-44f2-ba31-2dcdc2ae9f6e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/span</value>
      <webElementGuid>95c61a77-80ad-4baa-a180-df9eaa29f730</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Login/Register' or . = 'Login/Register')]</value>
      <webElementGuid>1b8e1cc4-fef3-47e2-afd5-bfb15ff57eaa</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
