<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_TL</name>
   <tag></tag>
   <elementGuidId>2eb16793-a860-4f20-9dfa-402d2f9aba54</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.MuiAvatar-root.MuiAvatar-circular.MuiAvatar-colorDefault.css-3agy0s</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='ulj-login']/span/div/div/div/div/button/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Profile&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>d0519526-7619-4009-903f-fa374d5d1a3e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiAvatar-root MuiAvatar-circular MuiAvatar-colorDefault css-3agy0s</value>
      <webElementGuid>8fcbb352-0cfc-4298-a8af-8bac9f2f193e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> TL </value>
      <webElementGuid>00efb015-4ffb-4ce8-b9cd-25f5b900c79d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ulj-login&quot;)/span[1]/div[@class=&quot;ulj-login&quot;]/div[@class=&quot;ulj-login-container&quot;]/div[@class=&quot;profilemenu&quot;]/div[@class=&quot;profilemenu-box flex al-center jc-center MuiBox-root css-0&quot;]/button[@class=&quot;MuiButtonBase-root MuiIconButton-root MuiIconButton-sizeSmall css-1j7qk7u&quot;]/div[@class=&quot;MuiAvatar-root MuiAvatar-circular MuiAvatar-colorDefault css-3agy0s&quot;]</value>
      <webElementGuid>b5f2652c-af18-44af-aee6-431e8c13b9ab</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ulj-login']/span/div/div/div/div/button/div</value>
      <webElementGuid>c4fa6be4-afc4-4762-9ba0-9da659ba7c06</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='New'])[1]/following::div[9]</value>
      <webElementGuid>cc45d9bf-fde4-41e6-b9e8-b2e2362949dd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='My Jobs'])[1]/following::div[10]</value>
      <webElementGuid>519081b9-297f-4991-95fc-795eb5ac99d7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Profile'])[1]/preceding::div[1]</value>
      <webElementGuid>5c96aa1b-a5a3-449a-a6bb-85d228a6a5f4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='TL']/parent::*</value>
      <webElementGuid>39834bcc-1e99-4bdb-b5a5-68a995de8ce3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button/div</value>
      <webElementGuid>85230c2c-db67-42a5-838e-5393f84282e7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = ' TL ' or . = ' TL ')]</value>
      <webElementGuid>395d2a50-2c1c-4090-a428-97cacab4cbef</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
